ASSIGN, 608
Type "tree" is undefined!
declaration_list (single)!
declaration_list (multiple)!
declaration_list (multiple)!
declaration_list (multiple)!
declaration_list (multiple)!
dblock!
ID, token: 101
EXPR_ASSIGNABLE, 915
return <expression>
<simple-statement> ;
{ ( <dblock> ) <statement-list> }
0, 1
NAME : SCOPE : PARENT : TYPE : EXTRA ANNOTATION
------------------------------------------------------
integer : 001001 :  : primitive : type
Boolean : 001001 :  : primitive : type
character : 001001 :  : primitive : type
string : 001001 :  : 1->character : type
identity : 001001 :  : integer->integer : function
i : 001001 :  : integer : local
b : 001001 :  : Boolean : local
c : 001001 :  : character : local
s : 001001 :  : string : local
t : 001001 :  : $_undefined_type : local
x : 001001 :  : integer : parameter of (identity)
